### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by SamSimp** [mtigas/django-gpg-sign-middleware#4]
Hi - I'm a Python newb but the cli.py does exactly what I needed...in theory.  I've run the program and I get: 

mbp:signweb sam$ python3 signweb.py liquid-2020-03-21.htm 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gnupg/_parsers.py", line 1094, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'FAILURE'
<!DOCTYPE html><html lang="en"></html>

I wonder if you had some pointers on how to resolve as I'm out of my depth

Thanks in advance

Sam

**Comment by SamSimp** [comment]
Ah, worth adding its gpg (GnuPG) 2.2.19...which maybe the problem!!
